// AUTO-GENERATED by scripts/fetch-nominee-photos.mjs — do not edit by hand.
// CC-licensed portraits from Wikimedia Commons, with attribution. Re-run to refresh.
import type { NomineeProfile } from "./types";

type ImageInfo = Pick<NomineeProfile, "image" | "imageAttribution" | "imageLicense" | "sourceUrl">;

export const nomineeImages: Record<string, ImageInfo> = {
  "Anand Kumar": {
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/24/AnandKumarJI1.jpg/500px-AnandKumarJI1.jpg",
    "imageLicense": "CC BY 2.0",
    "imageAttribution": "Joi Ito / Wikimedia Commons (CC BY 2.0)",
    "sourceUrl": "https://en.wikipedia.org/wiki/Anand_Kumar"
  },
  "Dr. Ravi Kannan": {
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/13/RavindranKannan.tiff/lossless-page1-120px-RavindranKannan.tiff.png",
    "imageLicense": "CC BY 2.5",
    "imageAttribution": "Unknown authorUnknown author / Wikimedia Commons (CC BY 2.5)",
    "sourceUrl": "https://en.wikipedia.org/wiki/Ravindran_Kannan"
  },
  "Dr. Devi Shetty": {
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/22/Devi_Shetty.jpg/500px-Devi_Shetty.jpg",
    "imageLicense": "CC BY 2.0",
    "imageAttribution": "Financial Times photos / Wikimedia Commons (CC BY 2.0)",
    "sourceUrl": "https://en.wikipedia.org/wiki/Devi_Shetty"
  },
  "Dr. Soumya Swaminathan": {
    "image": "https://upload.wikimedia.org/wikipedia/commons/b/ba/The_Director_General%2C_ICMR_and_Secretary%2C_DHR%2C_Dr._Soumya_Swaminathan%2C_in_New_Delhi_on_January_19%2C_2016.jpg",
    "imageLicense": "GODL-India",
    "imageAttribution": "Ministry of Health and Family Welfare / Wikimedia Commons (GODL-India)",
    "sourceUrl": "https://en.wikipedia.org/wiki/Soumya_Swaminathan"
  },
  "Nandan Nilekani": {
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/62/Nandan_M._Nilekani.jpg/500px-Nandan_M._Nilekani.jpg",
    "imageLicense": "CC BY-SA 2.0",
    "imageAttribution": "World Economic Forum from Cologny, Switzerland / Wikimedia Commons (CC BY-SA 2.0)",
    "sourceUrl": "https://en.wikipedia.org/wiki/Nandan_Nilekani"
  },
  "Kiran Mazumdar-Shaw": {
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Kiran_Mazumdar-Shaw_HD2014_crop.jpg/500px-Kiran_Mazumdar-Shaw_HD2014_crop.jpg",
    "imageLicense": "CC BY-SA 3.0",
    "imageAttribution": "Sofia Negron / Wikimedia Commons (CC BY-SA 3.0)",
    "sourceUrl": "https://en.wikipedia.org/wiki/Kiran_Mazumdar-Shaw"
  },
  "Raghuram Rajan": {
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Raghuram_Rajan%2C_IMF_69MS040421048l.jpg/500px-Raghuram_Rajan%2C_IMF_69MS040421048l.jpg",
    "imageLicense": "Public domain",
    "imageAttribution": "International Monetary Fund / Wikimedia Commons (Public domain)",
    "sourceUrl": "https://en.wikipedia.org/wiki/Raghuram_Rajan"
  },
  "Sunita Narain": {
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Sunita_Narain_CSE.jpg/500px-Sunita_Narain_CSE.jpg",
    "imageLicense": "CC BY-SA 2.5 in",
    "imageAttribution": "Center for Science and Education / Wikimedia Commons (CC BY-SA 2.5 in)",
    "sourceUrl": "https://en.wikipedia.org/wiki/Sunita_Narain"
  },
  "Dr. Madhav Gadgil": {
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f7/Prof.Madhav_Gadgil.jpg/500px-Prof.Madhav_Gadgil.jpg",
    "imageLicense": "CC BY-SA 4.0",
    "imageAttribution": "Syed Shiyaz Mirza / Wikimedia Commons (CC BY-SA 4.0)",
    "sourceUrl": "https://en.wikipedia.org/wiki/Madhav_Gadgil"
  },
  "Jadav Payeng": {
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Jadav_Payeng_Forest_Man_Of_India.jpg/500px-Jadav_Payeng_Forest_Man_Of_India.jpg",
    "imageLicense": "CC BY-SA 3.0",
    "imageAttribution": "Jadav Payeng / Wikimedia Commons (CC BY-SA 3.0)",
    "sourceUrl": "https://en.wikipedia.org/wiki/Jadav_Payeng"
  },
  "Justice (Retd.) Madan Lokur": {
    "image": "https://upload.wikimedia.org/wikipedia/commons/9/91/The_Judge%2C_Supreme_Court_of_India%2C_Justice_Madan_B._Lokur_delivering_the_valedictory_address%2C_at_the_35th_National_Symposium_of_Heads_of_Police_Training_Institutions%2C_in_New_Delhi_on_March_24%2C_2017_%28cropped%29.jpg",
    "imageLicense": "GODL-India",
    "imageAttribution": "Ministry of Law and Justice / Wikimedia Commons (GODL-India)",
    "sourceUrl": "https://en.wikipedia.org/wiki/Madan_Lokur"
  },
  "Justice (Retd.) B. N. Srikrishna": {
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Justice_%28Retd%29_B.N._Srikrishna_presented_the_Srikrishna_Committee_Report_on_Consultations_with_political_parties_and_groups_in_Andhra_Pradesh_on_Telangana_issue_to_the_Union_Home_Minister%2C_Shri_P._Chidambaram%2C_in_New_Delhi.jpg/500px-thumbnail.jpg",
    "imageLicense": "GODL-India",
    "imageAttribution": "Ministry of Home Affairs / Wikimedia Commons (GODL-India)",
    "sourceUrl": "https://en.wikipedia.org/wiki/B._N._Srikrishna"
  },
  "Aruna Roy": {
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Aruna_Roy_%282019%29.jpg/500px-Aruna_Roy_%282019%29.jpg",
    "imageLicense": "CC BY-SA 3.0",
    "imageAttribution": "Augustus Binu : flickr / Wikimedia Commons (CC BY-SA 3.0)",
    "sourceUrl": "https://en.wikipedia.org/wiki/Aruna_Roy"
  },
  "Abhinav Bindra": {
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Abhinav_Bindra_and_Mary_Kom_-_British_High_Commission%2C_Delhi%2C_27_July_2011_%28cropped%29.jpg/500px-Abhinav_Bindra_and_Mary_Kom_-_British_High_Commission%2C_Delhi%2C_27_July_2011_%28cropped%29.jpg",
    "imageLicense": "OGL v1.0",
    "imageAttribution": "British High Commission, India / Wikimedia Commons (OGL v1.0)",
    "sourceUrl": "https://en.wikipedia.org/wiki/Abhinav_Bindra"
  },
  "Pullela Gopichand": {
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Pullela_Gopichand_2016_%28cropped%29.jpg/500px-Pullela_Gopichand_2016_%28cropped%29.jpg",
    "imageLicense": "GODL-India",
    "imageAttribution": "Prime Minister's Office / Wikimedia Commons (GODL-India)",
    "sourceUrl": "https://en.wikipedia.org/wiki/Pullela_Gopichand"
  },
  "Dr. K. Sivan": {
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/K._Sivan.jpg/500px-K._Sivan.jpg",
    "imageLicense": "GODL-India",
    "imageAttribution": "Indian Space Research Organisation / Wikimedia Commons (GODL-India)",
    "sourceUrl": "https://en.wikipedia.org/wiki/K._Sivan"
  },
  "Dr. Manjul Bhargava": {
    "image": "https://upload.wikimedia.org/wikipedia/commons/d/d1/Manjul_Bhargava_FieldsMedal.jpg",
    "imageLicense": "FAL",
    "imageAttribution": "IMU / Wikimedia Commons (FAL)",
    "sourceUrl": "https://en.wikipedia.org/wiki/Manjul_Bhargava"
  },
  "Dr. M. S. Swaminathan": {
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Monkombu_Sambasivan_Swaminathan_-_Kolkata_2013-01-07_2674.JPG/500px-Monkombu_Sambasivan_Swaminathan_-_Kolkata_2013-01-07_2674.JPG",
    "imageLicense": "CC BY 3.0",
    "imageAttribution": "Biswarup Ganguly / Wikimedia Commons (CC BY 3.0)",
    "sourceUrl": "https://en.wikipedia.org/wiki/M._S._Swaminathan"
  },
  "Subhash Palekar": {
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Subhas_Palekar.JPG/500px-Subhas_Palekar.JPG",
    "imageLicense": "CC BY-SA 4.0",
    "imageAttribution": "Amitabhpatra / Wikimedia Commons (CC BY-SA 4.0)",
    "sourceUrl": "https://en.wikipedia.org/wiki/Subhash_Palekar"
  },
  "Sunitha Krishnan": {
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5f/Sunitha_Krishnan_at_Kollam_2025_2.jpg/500px-Sunitha_Krishnan_at_Kollam_2025_2.jpg",
    "imageLicense": "CC BY-SA 4.0",
    "imageAttribution": "Fotokannan / Wikimedia Commons (CC BY-SA 4.0)",
    "sourceUrl": "https://en.wikipedia.org/wiki/Sunitha_Krishnan"
  },
  "Safeena Husain": {
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Safeena_Husain_at_Jaipur_Literature_Festival_2026_01.jpg/500px-Safeena_Husain_at_Jaipur_Literature_Festival_2026_01.jpg",
    "imageLicense": "CC BY-SA 4.0",
    "imageAttribution": "Suyash Dwivedi / Wikimedia Commons (CC BY-SA 4.0)",
    "sourceUrl": "https://en.wikipedia.org/wiki/Safeena_Husain"
  },
  "Faye D'Souza": {
    "image": "https://upload.wikimedia.org/wikipedia/commons/c/cf/Faye_D%27Souza_%28cropped%29.jpg",
    "imageLicense": "CC BY-SA 4.0",
    "imageAttribution": "Ankycullen5 / Wikimedia Commons (CC BY-SA 4.0)",
    "sourceUrl": "https://en.wikipedia.org/wiki/Faye_D'Souza"
  },
  "Sucheta Dalal": {
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Sucheta_Dalal_in_2019.png/500px-Sucheta_Dalal_in_2019.png",
    "imageLicense": "CC BY 3.0",
    "imageAttribution": "NewsClickin / Wikimedia Commons (CC BY 3.0)",
    "sourceUrl": "https://en.wikipedia.org/wiki/Sucheta_Dalal"
  },
  "E. Sreedharan": {
    "image": "https://upload.wikimedia.org/wikipedia/commons/e/e3/E._Sreedharan_%22Metro_Man%22.jpg",
    "imageLicense": "GODL-India",
    "imageAttribution": "Vice President's Secretariat / Wikimedia Commons (GODL-India)",
    "sourceUrl": "https://en.wikipedia.org/wiki/E._Sreedharan"
  },
  "Sheela Patel": {
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/2011_World_Water_Week_Opening_Plenary_Monday_11.jpg/500px-2011_World_Water_Week_Opening_Plenary_Monday_11.jpg",
    "imageLicense": "CC BY 2.0",
    "imageAttribution": "World Water Week / Wikimedia Commons (CC BY 2.0)",
    "sourceUrl": "https://en.wikipedia.org/wiki/Sheela_Patel"
  },
  "Pandit Hariprasad Chaurasia": {
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Hariprasad_Chaurasia_in_July_2015_%281%29.jpg/500px-Hariprasad_Chaurasia_in_July_2015_%281%29.jpg",
    "imageLicense": "CC BY-SA 4.0",
    "imageAttribution": "Suyash Dwivedi / Wikimedia Commons (CC BY-SA 4.0)",
    "sourceUrl": "https://en.wikipedia.org/wiki/Hariprasad_Chaurasia"
  },
  "Sonal Mansingh": {
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Sonal_Mansingh.jpg/500px-Sonal_Mansingh.jpg",
    "imageLicense": "CC BY 3.0",
    "imageAttribution": "Ramesh Lalwani / Wikimedia Commons (CC BY 3.0)",
    "sourceUrl": "https://en.wikipedia.org/wiki/Sonal_Mansingh"
  },
  "Jatin Das": {
    "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a3/Jatindranath_Das_alias_Khedu.jpg/500px-Jatindranath_Das_alias_Khedu.jpg",
    "imageLicense": "Public domain",
    "imageAttribution": "UnknownUnknown / Wikimedia Commons (Public domain)",
    "sourceUrl": "https://en.wikipedia.org/wiki/Jatindra_Nath_Das"
  }
};
