import type { SortitionContent } from "./types";
import type { Source } from "./evidence/types";

// First draft for human review. All copy is part of a non-partisan reform
// proposal pursued through lawful, constitutional means: pilots, deliberation,
// and a public mandate. Nothing here calls for bypassing the Constitution.

export const sortition: SortitionContent = {
  hero: {
    eyebrow: "An idea older than elections",
    title: "What if we chose our representatives the way Athens did: by lot?",
    sub: "Sortition means filling a legislature with ordinary citizens drawn by stratified random selection, so the people who make the laws actually look like the people who live under them. It is not a coup or a shortcut. It is a reform to be tested, debated, and adopted only with a public mandate.",
  },

  whatItIs: {
    title: "What sortition actually is",
    body: [
      "Sortition is the selection of public officials by lottery rather than by election. Instead of campaigns, donations, and party tickets, a representative sample of citizens is drawn at random to deliberate and decide. Athenian democracy, roughly 2,500 years ago, filled most of its offices this way.",
      "The modern version is more careful than a raw draw. It uses stratified random sampling: the lottery is balanced so the final group mirrors the wider population by gender, age, region, and other characteristics. The result is a small assembly that statistically resembles the country as a whole.",
      "This is a proposal to study and pilot, not a finished blueprint. It would be introduced gradually, alongside our existing institutions, and would only scale if citizens choose it through legitimate, constitutional channels.",
    ],
  },

  howIndia: {
    title: "How it could work in India",
    intro:
      "India is vast and diverse, which is exactly why a randomly drawn assembly could represent it more faithfully than any single ballot can. Here is one careful design, offered for debate rather than as a fixed plan.",
    points: [
      {
        title: "Stratified random selection from every constituency",
        body: "Citizens would be drawn by lottery from across the country and balanced to mirror India by gender, caste, region, age, and income. The aim is an assembly that statistically resembles the nation, not a privileged slice of it.",
      },
      {
        title: "Short, fixed terms",
        body: "Each cohort would serve a short, fixed term measured in months or a few years, not careers. Power that is held briefly is far harder to hoard or sell.",
      },
      {
        title: "Built-in rotation",
        body: "Members would rotate out on a schedule, with fresh citizens drawn to replace them. Continuous turnover keeps the assembly close to the public and prevents a permanent political class from forming.",
      },
      {
        title: "No campaigning and no money",
        body: "Because seats are assigned by lot, there are no campaigns to fund and no donors to repay. Removing the money from selection removes one of the strongest incentives for capture.",
      },
      {
        title: "Paid service and full support",
        body: "Members would receive a fair salary, leave protection for their jobs, travel, childcare, and accessibility support. Ordinary people, including farmers, nurses, and daily-wage earners, must be able to say yes without losing their livelihood.",
      },
      {
        title: "Expert briefings on tap",
        body: "Citizens are not expected to be specialists. They would receive balanced briefings from civil servants, subject experts, and stakeholders on every side, so decisions rest on evidence rather than slogans.",
      },
    ],
  },

  whySmall: {
    title: "Why a smaller house deliberates better",
    body: "Real deliberation needs rooms where people can actually hear one another. A house of several hundred can debate; a house of many hundreds tends to perform. A smaller chamber of citizens, properly briefed and free to speak, can reason through a problem together in a way a crowded hall cannot. This is an argument about deliberation, not about reducing representation, since the sample is designed to mirror the whole country.",
    currentCount: 543,
    currentLabel: "Lok Sabha seats",
    proposedCount: 200,
    proposedLabel: "citizen legislators",
  },

  separation: {
    title: "Sortition does not stand alone",
    intro:
      "A randomly chosen legislature is one pillar among several. The strength of the design comes from keeping power divided, so that no single body, and no single person, can capture the state. Rotation and oversight reinforce each separation.",
    pillars: [
      {
        name: "Sortition legislature",
        body: "Makes and debates laws. Because its members are drawn by lot, serve briefly, and rotate out, there is no lasting bloc to bribe, threaten, or build a faction around.",
      },
      {
        name: "Independent judiciary",
        body: "Interprets the Constitution and checks every law and action against it. It stays independent of the assembly so that the rule of law, not the mood of the moment, has the final word.",
      },
      {
        name: "Accountable executive",
        body: "Carries out the laws under clear mandates, fixed limits, and constant scrutiny. It answers to the legislature and the courts and never sits above them.",
      },
      {
        name: "Free press",
        body: "Watches all three and informs the public. A free, independent press is the early-warning system that makes capture visible while there is still time to correct it.",
      },
    ],
  },

  howItChanges: {
    title: "What this would change",
    points: [
      {
        icon: "Users",
        title: "Representation that actually mirrors India",
        body: "A stratified random sample reflects the country by gender, caste, region, age, and income far more reliably than the people who can win and fund a campaign.",
      },
      {
        icon: "ShieldCheck",
        title: "Resistance to corruption",
        body: "With no campaigns to finance and members rotating out on short terms, the usual levers of bribery and patronage have far less to grip.",
      },
      {
        icon: "Scale",
        title: "Real deliberation over performance",
        body: "Citizens briefed by experts and free from re-election pressure can weigh evidence and trade-offs honestly, rather than playing to the next vote.",
      },
      {
        icon: "Vote",
        title: "Every citizen genuinely matters",
        body: "When seats are filled by lot, any citizen could be called to serve. Participation stops being something only the connected or wealthy can access.",
      },
      {
        icon: "Repeat",
        title: "Power that keeps moving",
        body: "Built-in rotation means no permanent political class. Influence is borrowed for a season and then handed back to the people.",
      },
      {
        icon: "Eye",
        title: "Decisions made in the open",
        body: "Briefings, debates, and votes can be transparent by design, giving the press and the public a clear view of how each law was reasoned.",
      },
    ],
  },

  precedents: {
    title: "Where this has already happened",
    items: [
      {
        place: "Ireland (2012–2018): the benchmark success",
        body: "Ireland ran two national citizen assemblies. The Convention on the Constitution (2013–14) mixed 66 randomly selected citizens with 33 politicians [c:ireland-conv-2013-14]; its recommendation on marriage equality led to a May 2015 referendum that passed with 62.07% — the first country to adopt same-sex marriage by popular vote [c:wiki-34th-ireland]. The follow-up Citizens' Assembly (2016–18), 99 randomly chosen citizens, deliberated on the Eighth Amendment over five weekends; 87% concluded the constitutional provision should not be retained in full [c:participedia-ireland-8th][c:ireland-ca-2016-18]. Parliament put repeal to referendum on 25 May 2018; it passed with 66.4% [c:wiki-36th-ireland]. Direct cost: €1,505,960.90 [c:ireland-ca-costs]. Caution: in March 2024, referendums arising from a later assembly on gender equality were defeated 67.7%–73.9% No [c:rte-referendum-2024], showing that assembly legitimacy does not transfer automatically when governments redraft proposals.",
      },
      {
        place: "France (2019–2020): the cautionary tale",
        body: "150 randomly selected residents deliberated from October 2019 to June 2020 on cutting emissions 40% \"in a spirit of social justice\" [c:elysee-ccc-2020]. The government promised proposals would go \"sans filtre\" to parliament or referendum and accepted 146 of 149 in June 2020 [c:elysee-ccc-2020]. Cost: €5.4 million including citizen compensation at €86.04 per day [c:ccc-budget]. What followed was the cautionary tale of the field: the resulting Climate and Resilience Law (August 2021) [c:vie-publique-ccc] visibly diluted the proposals — the citizens' ban on domestic flights where rail alternatives exist under 4 hours became 2.5 hours. Reporterre counted only about 10% of proposals taken up without modification [c:reporterre-ccc]; the citizens themselves graded the government's follow-through at 3.3 out of 10 [c:reporterre-ccc]. The institutional lesson: a response mechanism must be legislated before the body is convened, not promised after it reports.",
      },
      {
        place: "Ostbelgien, Belgium (2019–present): permanent sortition",
        body: "In February 2019, the parliament of Belgium's German-speaking community (population ~78,000) unanimously adopted a decree creating a permanent Citizens' Council of 24 members filled by lot, with one-third of seats replaced every six months [c:g1000-ostbelgien][c:oidp-ostbelgien]. The Council sets topics and commissions Citizens' Assemblies of 25–50 people drawn by lot — including 16-year-olds and non-citizen residents — with paid participation. Parliament is decree-bound to debate every recommendation with citizens present. Five years in, six assemblies have run and evaluators report deliberative norms \"slowly but surely\" taking root [c:pubdelib-ostbelgien-5yr]. This is the proof-of-concept for institutionalised, not one-off, sortition.",
      },
      {
        place: "Iceland (2011–2013): how a deliberative constitution dies",
        body: "After the 2008 financial crash, Iceland convened a National Forum of 950 randomly selected citizens, then a 25-member elected Constitutional Council that crowdsourced a draft constitution online [c:opendem-iceland]. In an October 2012 advisory referendum, two-thirds of voters approved the draft [c:quartz-iceland]. Parliament then never ratified it; the Althing was dissolved in 2013 without a vote and successor parliaments raised the ratification bar [c:opendem-iceland][c:quartz-iceland]. The lesson: a deliberative product with no binding pathway and no elite buy-in can be killed by silence. This failure mode — not public rejection but parliamentary attrition — is the one an Indian assembly design must engineer against.",
      },
      {
        place: "India: gram sabhas and Kerala's People's Plan",
        body: "No Indian government has yet commissioned a sortition-based citizens' assembly of the OECD type. But two bodies of evidence matter. Sanyal and Rao's Oral Democracy (Cambridge, 2018), built on transcripts of nearly 300 gram sabha meetings in South India, calls village assemblies \"the largest deliberative institution in human history\" [c:sanyal-rao-2018]; a companion World Bank study of 127 transcripts found these meetings democratically representative [c:wb-gramsabha-2017][c:wb-gramsabha-voice]. Kerala's People's Plan Campaign (1996–) devolved 35–40% of the state plan budget to local governments through gram sabhas and development seminars, mobilising millions and generating roughly 150,000 local projects in the Ninth Plan period [c:participedia-kerala][c:lsgd-kerala]. Both also document real weaknesses: women's participation lagged, local elite capture occurred, and Kerala's initial momentum declined. India has the institutional substrate for citizen deliberation; what is missing is sortition design.",
      },
    ],
  },

  constitutionalPath: {
    title: "The constitutional path",
    intro:
      "Every step of a credible Indian sortition programme up to and including a national advisory citizens' assembly requires no constitutional amendment. Only a body with binding legislative power would require amendment — and that path is constitutionally hazardous. Each phase below can be launched with the legal instrument named.",
    steps: [
      {
        tag: "Phase 1",
        label: "Panchayat and gram sabha pilots",
        body: "Randomly selected deliberative panels in 500–1,000 gram panchayats across 3–4 willing states, deliberating on local planning questions and placing reasoned recommendations before the panchayat's development plan process. India currently has roughly 2.6 lakh panchayats with over 31 lakh elected representatives, about 46% of them women [c:babushahi-46pct][c:mospi-ewrpri] — the institutional substrate exists. The Ministry of Panchayati Raj's Devolution Index 2024 puts the national average at 43.9 out of 100, with Karnataka highest at 72.2 [c:mopr-devolution-2024] — devolution is real and barely half-done.",
        legalNote: "State government order or rules under the existing state Panchayati Raj Act. No statute required. Article 243A gives state legislatures plenary power over gram sabha functions [c:art-243a]; Article 243G does the same for panchayat self-government powers [c:mopr-73rd-amendment].",
      },
      {
        tag: "Phase 2",
        label: "District-level deliberative councils",
        body: "Citizens' juries of 30–50 people on a concrete allocative question — untied-fund priorities, waste management, mobility — drawn from municipal corporation electoral rolls. The OECD database shows 52% of all documented deliberative processes have been at the local level [c:oecd-deliberative-2020], making this the best-evidenced tier. Success criteria: government written response within 90 days; baseline-vs-endline knowledge surveys replicating international knowledge-gain findings [c:fishkin-stanford][c:fishkin-2018] in Indian conditions.",
        legalNote: "Municipal corporation resolution or district planning committee decision under Article 243ZD. Ward committees under Article 243S as the anchor in cities. State executive order suffices; no statute required [c:mopr-73rd-amendment].",
      },
      {
        tag: "Phase 3",
        label: "State citizens' assemblies",
        body: "A first State Citizens' Assembly of 100–150 members, stratified by gender, caste, region, age and income from the state electoral roll, convened for one named question, chaired by a retired High Court or Supreme Court judge on the Irish model [c:participedia-ireland-8th]. Precedent: Ireland's 2016–18 Assembly was 99 members, five weekends, €1.5 million [c:ireland-ca-2016-18][c:ireland-ca-costs]. The selection methodology must be published and pre-cleared with the state's law department against Articles 14–16 before the assembly is convened — an open legal question that requires practitioner-reviewed opinion [c:art-243a].",
        legalNote: "State statute creating the assembly, the response obligation (government must table a reasoned reply in the Vidhan Sabha within six months), and member protections including paid leave and per-diems at jury-equivalent rates. No central permission needed. State executive power under Article 162 is coextensive with state legislative power.",
      },
      {
        tag: "Phase 4",
        label: "National advisory assembly",
        body: "A national advisory citizens' assembly drawn from ECI electoral rolls — 96.88 crore registered electors as of January 2024 [c:pib-eci-electorate-2024] — with multilingual facilitation. One national question with referendum-or-statute execution potential. Report laid before both Houses; standing-committee examination; government reasoned response within six months. NITI Aayog was created by a Cabinet Secretariat resolution dated 1 January 2015 — no statute, no amendment [c:niti-resolution-2015] — demonstrating the precedent for a resolution-based national advisory body. Selection uses peer-reviewed algorithms [c:flanigan-2021] published in advance with a full audit trail.",
        legalNote: "Preferably an ordinary Act of Parliament (simple majority) establishing a permanent national citizens' assembly system, fixing its selection method, funding it, and binding the government to respond. Minimally a Cabinet resolution on the NITI Aayog precedent [c:niti-resolution-2015]. Neither route touches Parliament's composition under Article 79 or legislative procedure, so no constitutional amendment is needed.",
      },
      {
        tag: "Phase 5",
        label: "Constitutional entrenchment — permanence, not power",
        body: "Statutory permanence on the Ostbelgien model [c:g1000-ostbelgien][c:pubdelib-ostbelgien-5yr]: a standing Citizens' Council that sets topics and monitors follow-up. Constitutional amendment only if India later chooses to give assemblies any binding trigger — which would invoke Article 368's special majority, likely state ratification, and basic-structure review [c:art-368][c:kesavananda-1973]. Giving any sortition body binding legislative power would require amending Part V (Articles 79–122) and face a serious basic-structure challenge: the Supreme Court held in Indira Nehru Gandhi v. Raj Narain (1975) that free and fair elections are part of the basic structure [c:indira-gandhi-1975], and a court could readily hold that 'democracy' as constitutionalised in India means electoral democracy. Phase 5 is treated as an open question, not a goal.",
        legalNote: "Advisory sortition requires no constitutional amendment. Binding sortition faces a special majority under Article 368(2) plus state ratification, plus basic-structure review under Kesavananda Bharati [c:kesavananda-1973] and Indira Gandhi [c:indira-gandhi-1975]. This brief does not recommend the binding path.",
      },
    ],
  },

  faqs: [
    {
      q: "What if a bad person is selected at random?",
      a: "A random sample only mirrors the population, so any single person is no worse, on average, than the rest of us. More importantly, no individual holds much power: terms are short, members rotate out, every decision is made by a deliberating group with expert support and oversight, and the separation of powers means the legislature cannot act alone. One poor draw cannot capture the system.",
    },
    {
      q: "These citizens have no experience. How can they govern?",
      a: "They are not asked to be technical experts. Like a jury, they receive balanced briefings, hear from specialists and stakeholders on every side, and deliberate before deciding. Elected politicians are rarely experts in the fields they legislate either; the difference is that randomly chosen citizens have no campaign or donor to please when they weigh the evidence.",
    },
    {
      q: "Isn't voting more democratic than a lottery?",
      a: "Both are democratic, but in different ways. Elections give everyone a vote yet tend to produce representatives who are wealthier, better connected, and more partisan than the public. A stratified lottery gives a fair chance of service to every kind of citizen and produces an assembly that statistically looks like the country. Sortition is offered as a complement to be tested, not a replacement to be imposed.",
    },
    {
      q: "Who decides what gets debated?",
      a: "Agendas can be set transparently: by the citizens themselves, by petitions that cross a public threshold, and by referrals from elected or constitutional bodies. The point is that the agenda is open and visible, not controlled behind closed doors by a party whip.",
    },
    {
      q: "How do laws actually pass?",
      a: "Much as they do now, but with deliberation at the centre. A proposal is briefed from all sides, debated in the assembly, refined, and put to a recorded vote. It must still pass constitutional scrutiny by an independent judiciary and be carried out by an accountable executive. No law is valid simply because the assembly wishes it.",
    },
    {
      q: "What stops a dictator, or capture by money or a faction?",
      a: "The design is built to resist exactly this. There are no campaigns to fund, so money loses its grip on selection. Short terms and constant rotation prevent a lasting bloc from forming. Power is split across an independent judiciary, an accountable executive, and a free press. Anyone trying to seize control would have to capture several rotating, independent institutions at once.",
    },
    {
      q: "Has this ever actually worked in practice?",
      a: "Yes. Athens governed by lot for generations. In our own time, OECD-documented citizens' assemblies have deliberated successfully across many countries since around 2010. Ireland's Citizens' Assembly shaped real national referendums, and Iceland used citizen participation in drafting constitutional proposals. Sortition has a long and a living track record.",
    },
    {
      q: "Is this a plan to overthrow the current system?",
      a: "No. This is a reform proposal and a thought experiment, to be pursued only through lawful, constitutional means. The path is small pilots, public deliberation, and a clear popular mandate at every step. Nothing here calls for bypassing the Constitution, the courts, or the will of the people.",
    },
    {
      q: "Wouldn't people refuse to serve?",
      a: "Service is made realistic, not forced into hardship. Members are paid a fair salary, their jobs are protected, and they receive travel, childcare, and accessibility support. Where service is treated with dignity, as jury duty is in many countries, citizens take it up seriously.",
    },
  ],

  chamber: {
    seats: 200,
    centerLabel: "The floor",
    sampleRoles: [
      "A schoolteacher from Bihar",
      "A nurse from Kerala",
      "A farmer from Punjab",
      "An auto driver from Pune",
      "A software engineer from Hyderabad",
      "A weaver from Varanasi",
      "A fisherwoman from Tamil Nadu",
      "A small shop owner from Indore",
      "A retired soldier from Himachal Pradesh",
      "A college student from Assam",
      "A construction worker from Delhi",
      "A doctor from rural Rajasthan",
      "A tea garden worker from West Bengal",
      "A homemaker from Gujarat",
    ],
  },

  sources: [
    {
      id: "oecd-deliberative-2020",
      org: "OECD",
      title: "Innovative Citizen Participation and New Democratic Institutions: Catching the Deliberative Wave",
      year: "2020",
      url: "https://www.oecd.org/en/publications/innovative-citizen-participation-and-new-democratic-institutions_339306da-en.html",
      note: "289 representative deliberative processes 1986–Oct 2019; level-of-government shares; OECD good-practice principles.",
      category: "multilateral",
    },
    {
      id: "mejia-oecd-2023",
      org: "Mauricio Mejia / OECD Participo",
      title: "2023 Trends in Deliberative Democracy: OECD Database Update",
      year: "2023",
      url: "https://medium.com/participo/2023-trends-in-deliberative-democracy-oecd-database-update-c8802935f116",
      note: "733 cases 1979–2023; 160 new processes Sept 2021–Sept 2023.",
      category: "multilateral",
    },
    {
      id: "fishkin-stanford",
      org: "Stanford Deliberative Democracy Lab",
      title: "What is Deliberative Polling?",
      year: "2026",
      url: "https://deliberation.stanford.edu/what-deliberative-pollingr",
      note: "Methodology overview; cross-poll summary of knowledge gains and opinion change across 18+ countries.",
      category: "research",
    },
    {
      id: "fishkin-2018",
      org: "James S. Fishkin",
      title: "Democracy When the People Are Thinking (Oxford University Press, 2018)",
      year: "2018",
      url: "https://cddrl.fsi.stanford.edu/people/James_S_Fishkin",
      note: "Synthesises three decades of Deliberative Polling data; ~70% of issues show significant opinion change with measurable knowledge gains.",
      category: "research",
    },
    {
      id: "flanigan-2021",
      org: "Flanigan B., Gölz S., Gupta A., Hennig B. & Procaccia A.",
      title: "Fair algorithms for selecting citizens' assemblies",
      year: "2021",
      url: "https://www.nature.com/articles/s41586-021-03788-6",
      note: "Nature 596 (2021). Peer-reviewed selection algorithms giving near-equal individual selection probabilities while meeting stratification quotas.",
      category: "research",
    },
    {
      id: "landemore-2020",
      org: "Hélène Landemore",
      title: "Open Democracy: Reinventing Popular Rule for the Twenty-First Century (Princeton UP, 2020)",
      year: "2020",
      url: "https://press.princeton.edu/books/hardcover/9780691181998/open-democracy",
      note: "Political theory case for randomly selected bodies as more literally democratic than elected chambers.",
      category: "research",
    },
    {
      id: "lafont-2020",
      org: "Cristina Lafont",
      title: "Democracy without Shortcuts: A Participatory Conception of Deliberative Democracy (OUP, 2020)",
      year: "2020",
      url: "https://philpapers.org/rec/LAFDWS-2",
      note: "Critique of 'blind deference' to mini-publics; concedes uses that feed rather than substitute for wider public deliberation.",
      category: "research",
    },
    {
      id: "adr-2024",
      org: "Association for Democratic Reforms",
      title: "Record 46% of newly-elected Lok Sabha MPs facing criminal cases",
      year: "2024",
      url: "https://adrindia.org/content/record-46-of-newly-elected-lok-sabha-mps-facing-criminal-cases",
      note: "Analysis of winning candidates' affidavits, 2024 general election; 251 of 543 MPs with criminal cases, 170 with serious cases; 93% crorepatis.",
      category: "other",
    },
    {
      id: "factly-women-mp-2024",
      org: "Factly",
      title: "Number of Women MPs Down to 74 in 18th Lok Sabha",
      year: "2024",
      url: "https://factly.in/data-number-of-women-mps-down-to-74-in-18th-lok-sabha-women-contestants-at-less-than-10/",
      note: "74 women elected to 18th Lok Sabha; 13.6% of the House, down from 14.4% in 2019.",
      category: "other",
    },
    {
      id: "pib-eci-electorate-2024",
      org: "Election Commission of India / PIB",
      title: "Largest electorate for General Elections — over 96.88 crore electors registered",
      year: "2024",
      url: "https://www.pib.gov.in/PressReleasePage.aspx?PRID=2005189",
      note: "Electoral rolls of 1 January 2024.",
      category: "official",
    },
    {
      id: "ireland-ca-2016-18",
      org: "Citizens' Assembly Ireland",
      title: "2016–2018 Citizens' Assembly (official site)",
      year: "2018",
      url: "https://citizensassembly.ie/previous-assemblies/2016-2018-citizens-assembly/",
      note: "99 randomly selected citizens; chaired by Supreme Court judge Mary Laffoy; deliberated November 2016–April 2017.",
      category: "official",
    },
    {
      id: "participedia-ireland-8th",
      org: "Participedia",
      title: "Irish Citizens' Assembly: the Eighth Amendment",
      year: "2018",
      url: "https://participedia.net/case/irish-citizens-assembly-the-eighth-amendment",
      note: "Case entry: 99 members, 87% voted that Article 40.3.3 should not be retained in full.",
      category: "other",
    },
    {
      id: "wiki-36th-ireland",
      org: "Wikipedia",
      title: "Thirty-sixth Amendment of the Constitution of Ireland",
      year: "2018",
      url: "https://en.wikipedia.org/wiki/Thirty-sixth_Amendment_of_the_Constitution_of_Ireland",
      note: "Referendum 25 May 2018; 66.4% Yes.",
      category: "other",
    },
    {
      id: "ireland-conv-2013-14",
      org: "Citizens' Assembly Ireland",
      title: "2013–2014 Convention on the Constitution",
      year: "2014",
      url: "https://citizensassembly.ie/previous-assemblies/2013-2014-convention-on-the-constitution/",
      note: "66 randomly selected citizens, 33 politicians, 1 independent chair.",
      category: "official",
    },
    {
      id: "wiki-34th-ireland",
      org: "Wikipedia",
      title: "Thirty-fourth Amendment of the Constitution of Ireland",
      year: "2015",
      url: "https://en.wikipedia.org/wiki/Thirty-fourth_Amendment_of_the_Constitution_of_Ireland",
      note: "Marriage equality referendum 22 May 2015; 62.07% Yes — first country to adopt same-sex marriage by popular vote.",
      category: "other",
    },
    {
      id: "ireland-ca-costs",
      org: "Citizens' Assembly Ireland",
      title: "Procurement and Costs",
      year: "2018",
      url: "https://2016-2018.citizensassembly.ie/en/About-the-Citizens-Assembly/Background/Procurement-and-Costs/",
      note: "Total budget €1,505,960.90 for the 2016–18 Assembly.",
      category: "official",
    },
    {
      id: "kildare-ca-costs-2024",
      org: "Kildare Nationalist",
      title: "Citizens' assemblies cost taxpayers over €6.8 million",
      year: "2024",
      url: "https://www.kildare-nationalist.ie/news/citizens-assemblies-cost-taxpayers-over-6-8-million-new-figures-reveal_arid-70304.html",
      note: "Cumulative spending on Ireland's citizens' assemblies; figures released 2024.",
      category: "other",
    },
    {
      id: "rte-referendum-2024",
      org: "RTÉ News",
      title: "Resounding defeat for Family referendum as 67.7% vote No",
      year: "2024",
      url: "https://www.rte.ie/news/ireland/2024/0309/1436882-referendum/",
      note: "9 March 2024; Family amendment 67.7% No; Care amendment 73.9% No — largest No vote in Irish referendum history.",
      category: "other",
    },
    {
      id: "elysee-ccc-2020",
      org: "Élysée",
      title: "Macron responds to 150 citizens of the Convention Citoyenne pour le Climat",
      year: "2020",
      url: "https://www.elysee.fr/emmanuel-macron/2020/06/29/le-president-emmanuel-macron-repond-aux-150-citoyens-de-la-convention-citoyenne-pour-le-climat",
      note: "29 June 2020; 146 of 149 proposals accepted.",
      category: "official",
    },
    {
      id: "ccc-budget",
      org: "Convention Citoyenne pour le Climat",
      title: "Le budget (official Convention budget)",
      year: "2020",
      url: "https://www.conventioncitoyennepourleclimat.fr/budget/",
      note: "Total €5.4 million; citizen per-diem €86.04/day.",
      category: "official",
    },
    {
      id: "reporterre-ccc",
      org: "Reporterre",
      title: "Convention pour le climat: seules 10% des propositions ont été reprises par le gouvernement",
      year: "2021",
      url: "https://reporterre.net/Convention-pour-le-climat-seules-10-des-propositions-ont-ete-reprises-par-le-gouvernement",
      note: "Citizens graded government follow-through at 3.3/10 in February 2021 final session.",
      category: "other",
    },
    {
      id: "knoca-ccc",
      org: "KNOCA",
      title: "French Citizens' Convention on the Climate",
      year: "2021",
      url: "https://www.knoca.eu/national-assemblies/french-citizens-convention-on-the-climate",
      note: "Implementation assessment: ~37% of proposals modified or partially implemented; rest weakened or dropped.",
      category: "other",
    },
    {
      id: "vie-publique-ccc",
      org: "Vie-publique.fr",
      title: "Loi du 22 août 2021 climat et résilience",
      year: "2021",
      url: "https://www.vie-publique.fr/loi/278460-loi-22-aout-2021-climat-et-resilience-convention-citoyenne-climat",
      note: "Legislative record; domestic-flight ban 2h30 vs convention's 4h proposal.",
      category: "official",
    },
    {
      id: "g1000-ostbelgien",
      org: "G1000",
      title: "Permanent Citizen Dialogue in Ostbelgien",
      year: "2019",
      url: "https://www.g1000.org/en/cases/permanent-citizen-dialogue-ostbelgien",
      note: "February 2019 decree; 24-member Citizens' Council filled by lot; assemblies of 25–50 by lot.",
      category: "other",
    },
    {
      id: "pubdelib-ostbelgien-5yr",
      org: "Deliberative Democracy Digest",
      title: "The Ostbelgien Model: five years on",
      year: "2024",
      url: "https://www.publicdeliberation.net/the-ostbelgien-model-five-years-on/",
      note: "Six assemblies run; evaluation findings including weaknesses; deliberative norms 'slowly but surely' taking root.",
      category: "other",
    },
    {
      id: "oidp-ostbelgien",
      org: "OIDP",
      title: "The Ostbelgien Model: a long-term Citizens' Council",
      year: "2024",
      url: "https://oidp.net/en/practice.php?id=1237",
      note: "Practice entry; selection mechanism and parliamentary response obligation.",
      category: "other",
    },
    {
      id: "opendem-iceland",
      org: "openDemocracy",
      title: "Democracy on ice: a post-mortem of the Icelandic constitution",
      year: "2013",
      url: "https://www.opendemocracy.net/en/can-europe-make-it/democracy-on-ice-post-mortem-of-icelandic-constitution/",
      note: "National Forum of 950 randomly selected citizens; 25-member Constitutional Council; parliamentary attrition without ratification.",
      category: "other",
    },
    {
      id: "quartz-iceland",
      org: "Quartz",
      title: "Iceland's experiment with crowd-sourcing its constitution just died",
      year: "2013",
      url: "https://qz.com/68910/icelands-experiment-with-crowd-sourcing-its-constitution-just-died",
      note: "October 2012 advisory referendum — two-thirds approval; no parliamentary ratification by 2013.",
      category: "other",
    },
    {
      id: "wb-gramsabha-2017",
      org: "World Bank / Parthasarathy & Rao",
      title: "Deliberative Democracy in India",
      year: "2017",
      url: "https://documents1.worldbank.org/curated/en/428681488809552560/pdf/WPS7995.pdf",
      note: "World Bank Policy Research Working Paper 7995. 127 gram sabha transcripts.",
      category: "research",
    },
    {
      id: "wb-gramsabha-voice",
      org: "Parthasarathy R., Rao V. & Palaniswamy N. / Stanford GSB",
      title: "Who Has Voice in a Deliberative Democracy? Evidence from Transcripts of Village Parliaments in South India",
      year: "2017",
      url: "https://www.gsb.stanford.edu/faculty-research/publications/who-has-voice-deliberative-democracy-evidence-transcripts-village",
      note: "127 gram sabha transcripts collected 2003; findings on who speaks and what gets discussed.",
      category: "research",
    },
    {
      id: "sanyal-rao-2018",
      org: "Sanyal P. & Rao V.",
      title: "Oral Democracy: Deliberation in Indian Village Assemblies (Cambridge University Press, 2018)",
      year: "2018",
      url: "https://www.cambridge.org/core/books/oral-democracy/1389E93F8F69AA1AB07B434124CE7582",
      note: "~300 gram sabha transcripts from South India; calls village assemblies 'the largest deliberative institution in human history'.",
      category: "research",
    },
    {
      id: "ideas-gramsabha",
      org: "Ideas for India",
      title: "How effective are gram sabhas?",
      year: "2024",
      url: "https://www.ideasforindia.in/topics/governance/how-effective-are-gram-sabhas",
      note: "Summarises Besley, Pande & Rao (2005, JEEA): attendance patterns, BPL targeting, women's under-participation.",
      category: "other",
    },
    {
      id: "participedia-kerala",
      org: "Participedia",
      title: "Kerala People's Campaign for Decentralized Planning",
      year: "2024",
      url: "https://participedia.net/case/35",
      note: "35–40% of state plan budget devolved; ₹1,025 crore in year one; ~150,000 local projects in Ninth Plan period.",
      category: "other",
    },
    {
      id: "lsgd-kerala",
      org: "Local Self-Government Department, Government of Kerala",
      title: "9th Five Year Plan — People's Plan Campaign",
      year: "2024",
      url: "https://lsgd.kerala.gov.in/en/evolution/power-to-the-people/",
      note: "Official campaign history and devolution figures.",
      category: "official",
    },
    {
      id: "mopr-73rd-amendment",
      org: "Ministry of Panchayati Raj",
      title: "73rd Constitutional Amendment Act, 1992",
      year: "2024",
      url: "https://panchayat.gov.in/en/document/73rd-constitutional-amendment-act-1992/",
      note: "Assented 20 April 1993 after ratification by state legislatures. Inserted Part IX (Articles 243–243O) and Part IXA (Articles 243P–243ZG).",
      category: "official",
    },
    {
      id: "art-243a",
      org: "Constitution of India",
      title: "Article 243A: Gram Sabha",
      year: "1993",
      url: "https://www.constitutionofindia.net/articles/article-243a-gram-sabha/",
      note: "Full text: 'A Gram Sabha may exercise such powers and perform such functions at the village level as the Legislature of a State may, by law, provide.'",
      category: "official",
    },
    {
      id: "art-368",
      org: "Constitution of India",
      title: "Article 368: Power of Parliament to amend the Constitution",
      year: "1949",
      url: "https://www.constitutionofindia.net/articles/article-368-power-of-parliament-to-amend-the-constitution-and-procedure-therefor/",
      note: "Clause (2) and proviso including state-ratification list for amendments touching representation of states, Centre-state relations and other listed subjects.",
      category: "official",
    },
    {
      id: "kesavananda-1973",
      org: "Supreme Court of India",
      title: "Kesavananda Bharati v. State of Kerala — basic structure doctrine (1973)",
      year: "1973",
      url: "https://www.scconline.com/blog/post/2023/04/24/kesavananda-bharati-vs-state-of-kerala/",
      note: "13-judge bench, 7–6, 24 April 1973. Parliament's amending power cannot destroy the Constitution's basic structure, which includes democracy, free and fair elections, federalism and judicial review.",
      category: "official",
    },
    {
      id: "indira-gandhi-1975",
      org: "Supreme Court of India",
      title: "Indira Nehru Gandhi v. Raj Narain — free and fair elections as basic structure (1975)",
      year: "1975",
      url: "https://indiankanoon.org/doc/936707/",
      note: "7 November 1975. Art 329A(4) and (5) struck down; first time an amendment was invalidated on basic-structure grounds. Free and fair elections confirmed as basic structure.",
      category: "official",
    },
    {
      id: "niti-resolution-2015",
      org: "Cabinet Secretariat, Government of India",
      title: "Cabinet Resolution establishing NITI Aayog",
      year: "2015",
      url: "https://www.niti.gov.in/sites/default/files/2022-11/Cabinet_Secretariat_Resolution_dated_01-01-2015.pdf",
      note: "Resolution dated 1 January 2015. NITI Aayog created by executive resolution — no statute, no amendment.",
      category: "official",
    },
    {
      id: "mopr-devolution-2024",
      org: "Ministry of Panchayati Raj / IIPA",
      title: "Devolution Index Report 2024",
      year: "2024",
      url: "https://panchayat.gov.in/en/notice/devolution-index-report-2024/",
      note: "National average 43.9 out of 100, up from 39.9 in 2013-14; Karnataka leads at 72.2.",
      category: "official",
    },
    {
      id: "mospi-ewrpri",
      org: "Ministry of Statistics and Programme Implementation",
      title: "State/UT-wise Elected Women Representatives in Panchayati Raj Institutions",
      year: "2024",
      url: "https://www.mospi.gov.in/stateut-wise-elected-women-representatives-panchayati-raj-institutions-pris",
      note: "Women approximately 46% of PRI elected representatives.",
      category: "official",
    },
    {
      id: "babushahi-46pct",
      org: "Babushahi",
      title: "14.5 lakh women make up 46% of elected representatives",
      year: "2025",
      url: "https://www.babushahi.com/full-news.php?id=208734",
      note: "Reporting Union Minister of Panchayati Raj statement, March 2025. ~2.6 lakh panchayats, ~31.5 lakh elected representatives.",
      category: "other",
    },
    {
      id: "stanford-ai-wearables",
      org: "Stanford FSI / CDDRL",
      title: "Deliberative Democracy Lab: AI Wearables findings",
      year: "2024",
      url: "https://cddrl.fsi.stanford.edu/news/deliberative-democracy-lab-releases-findings-public-attitudes-toward-ai-wearables",
      note: "550 participants: 300 US, 250 India. Demonstrates methodological feasibility of Deliberative Polling with Indian samples.",
      category: "research",
    },
    {
      id: "trinity-amr-dp",
      org: "The Trinity Challenge",
      title: "Global Deliberative Poll on antibiotic resistance (including India)",
      year: "2024",
      url: "https://thetrinitychallenge.org/news-and-stories/the-trinity-challenge-partners-with-stanford-university-in-first-of-its-kind-global-deliberative-poll-on-antibiotic-resistance/",
      note: "Pilot in six low- and middle-income countries including India. Demonstrates recruitment, stratification, and multilingual facilitation at Indian scale.",
      category: "research",
    },
    {
      id: "adr-election-cost-2024",
      org: "ADR / Centre for Media Studies",
      title: "2024 LS polls pegged as costliest ever, expenditure may touch ₹1.35 lakh crore",
      year: "2024",
      url: "https://adrindia.org/content/2024-ls-polls-pegged-costliest-ever-expenditure-may-touch-rs-135-lakh-crore",
      note: "CMS estimate of total expenditure around the 2024 Lok Sabha election. The entire five-year sortition programme is approximately 0.1–0.2% of one election cycle.",
      category: "other",
    },
    {
      id: "ers-ireland-2018",
      org: "Electoral Reform Society",
      title: "The Irish abortion referendum: How a Citizens' Assembly helped to break years of political deadlock",
      year: "2018",
      url: "https://electoral-reform.org.uk/the-irish-abortion-referendum-how-a-citizens-assembly-helped-to-break-years-of-political-deadlock/",
      note: "Advocates credit the assembly with breaking a 35-year political deadlock; attribution is contested and counterfactual is unknowable.",
      category: "other",
    },
    {
      id: "pepperdine-dp",
      org: "Pepperdine / Davenport Institute",
      title: "Deliberative Polling Project",
      year: "2026",
      url: "https://publicpolicy.pepperdine.edu/davenport-institute/projects/deliberative-polling.htm",
      note: "Tertiary summary citing Fishkin's Stanford data; primary sources are fishkin-stanford and fishkin-2018.",
      category: "other",
    },
  ] satisfies Source[],
};
